server:
  host: 0.0.0.0
  port: 8080
  read_timeout: 1m
  write_timeout: 1m
  session_key: "frrist-w3infra-storage-provider"

onboarding:
  session_timeout: 12h
  fqdn_verification_timeout: 1m
  indexing_service_key: "MgCa5lObwi7YoN08khh0sVmK0cqv9wR9bUeJLz3osyYem3+0Bh5Ank+zu2EIeJ/Tpy2gdxMRmIJSBGIEl6FtMAsJwZzE="
  upload_service_did: "did:key:z6Mktg7STK3Sh2x7F1NVNfctNG55hN7EG6cMhsdCKqFZ5rWz"
  allow_list:
    - "did:key:z6MksvRCPWoXvMj8sUzuHiQ4pFkSawkKRz2eh1TALNEG6s3e"

log:
  level: debug

dynamo:
  region: us-west-1
  endpoint: http://dynamodb-local:8000
  allow_list_table_name: delegator-allow-list
  provider_info_table_name: delegator-provider-info