FROM amazon/aws-cli:2.13.18

WORKDIR /setup

# Install curl for checking if DynamoDB is ready
RUN yum install -y curl && yum clean all

# Copy setup script
COPY ./docker/setup-dynamodb.sh .

# Make script executable
RUN chmod +x setup-dynamodb.sh

# Set entry point to bash to allow the script to run
ENTRYPOINT ["/bin/bash"]
CMD ["./setup-dynamodb.sh"]